spring.application.name=api-service

# Run this service on a different port to avoid conflicts
server.port=8081

# Connect to the API service database
spring.datasource.url=jdbc:h2:file:~/synapsedb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Enable H2 console (optional here, but can be useful)
spring.h2.console.enabled=true