spring.application.name=core-engine

# Core engine database
spring.datasource.url=jdbc:h2:file:~/synapsedb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# H2 Console settings
spring.h2.console.enabled=true

# Kafka bootstrap server
spring.kafka.bootstrap-servers=localhost:9092