spring.application.name=core-engine
# Connect to an in-memory H2 database named 'testdb'
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Let JPA create the tables for us automatically from our @Entity classes
spring.jpa.hibernate.ddl-auto=create-drop

# Enable the H2 Console, a simple web tool to view our database
spring.h2.console.enabled=true